# Traceback (most recent call last):
#   File "C:\Users\Alla\Desktop\Академия\SQL\home_work_6.py", line 107, in <module>
#     db.add_note(text_note, rating_note, user_id)
#   File "C:\Users\Alla\Desktop\Академия\SQL\home_work_6.py", line 30, in add_note
#     with sqlite3.connect(self.db_name) as con:
# sqlite3.OperationalError: database is locked